# -*- coding: utf-8 -*-
# Generated by https://github.com/verloop/twirpy/protoc-gen-twirpy.  DO NOT EDIT!
# source: calculator.proto

from google.protobuf import symbol_database as _symbol_database

from twirp.base import Endpoint
from twirp.server import TwirpServer
from twirp.client import TwirpClient

_sym_db = _symbol_database.Default()


class CalculatorServer(TwirpServer):
    def __init__(self, *args, service, server_path_prefix="/twirp"):
        super().__init__(service=service)
        self._prefix = f"{server_path_prefix}/.Calculator"
        self._endpoints = {
            "SquareRoot": Endpoint(
                service_name="Calculator",
                name="SquareRoot",
                function=getattr(service, "SquareRoot"),
                input=_sym_db.GetSymbol("Number"),
                output=_sym_db.GetSymbol("Number"),
            ),
        }


class CalculatorClient(TwirpClient):
    def SquareRoot(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/.Calculator/SquareRoot",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("Number"),
            **kwargs,
        )
